https://www.kaggle.com/birdy654/eeg-brainwave-dataset-mental-state/code

Relaxed, concentrating, neutral classification problem
Steps to solving 

1. Seperate label column
2. Check labels column is balanced
3. Make labels numeric
4. Split train test dataset
5. Define reccurent model
6. Apply dataset to model
7. Test model
8. Succeed / start with 5 again

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow
from tensorflow import keras
from keras.layers import Dense

In [3]:
data = pd.read_csv('mental-state.csv')
data.head()

,lag1_mean_0,lag1_mean_1,lag1_mean_2,lag1_mean_3,lag1_mean_d_h2h1_0,lag1_mean_d_h2h1_1,lag1_mean_d_h2h1_2,lag1_mean_d_h2h1_3,lag1_mean_q1_0,lag1_mean_q1_1,...,freq_669_3,freq_679_3,freq_689_3,freq_699_3,freq_709_3,freq_720_3,freq_730_3,freq_740_3,freq_750_3,Label
0,25.781648,33.836367,-92.769629,19.187957,-1.542262,0.197462,-119.561133,2.032654,21.596272,33.965587,...,0.000230,0.000351,0.000547,0.000381,0.000350,0.000453,0.000442,0.000325,0.000209,2.0
1,29.357891,26.792566,417.203910,19.472121,-38.797263,-16.897194,-29.368531,-9.055370,44.647424,40.893307,...,0.001671,0.000740,0.001122,0.000521,0.000624,0.000439,0.001249,0.000727,0.000801,2.0
2,28.451926,31.076434,72.231301,14.245938,-13.225057,-0.614138,-28.331698,-8.858742,31.450289,30.692883,...,0.000748,0.000569,0.000327,0.000197,0.000833,0.000909,0.000699,0.001165,0.000616,2.0
3,21.282184,19.985184,16.220094,39.787312,1.847866,0.670216,-1.820355,20.220724,21.404679,20.777411,...,0.000990,0.005644,0.006891,0.010546,0.009583,0.011158,0.008853,0.004551,0.002287,1.0
4,20.431516,28.982168,27.540246,19.960398,2.491458,-6.020503,-1.071166,2.655259,16.295039,32.658163,...,0.001659,0.014379,0.014492,0.002949,0.004575,0.008305,0.007202,0.006957,0.009836,2.0

In [4]:
data.isnull().sum().sum()

0

In [5]:
data.shape

(2479, 989)

In [7]:
data['Label'].value_counts()

2.0    830
1.0    830
0.0    819
Name: Label, dtype: int64

In [8]:
labels = data['Label'].copy()
data = data.drop('Label', axis = 1).copy()

In [9]:
print(labels)

0       2.0
1       2.0
2       2.0
3       1.0
4       2.0
       ...
2474    0.0
2475    2.0
2476    2.0
2477    2.0
2478    1.0
Name: Label, Length: 2479, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size = 0.2, random_state = 123)

In [17]:
X_train.head(3)

,lag1_mean_0,lag1_mean_1,lag1_mean_2,lag1_mean_3,lag1_mean_d_h2h1_0,lag1_mean_d_h2h1_1,lag1_mean_d_h2h1_2,lag1_mean_d_h2h1_3,lag1_mean_q1_0,lag1_mean_q1_1,...,freq_659_3,freq_669_3,freq_679_3,freq_689_3,freq_699_3,freq_709_3,freq_720_3,freq_730_3,freq_740_3,freq_750_3
1029,47.035227,33.077242,-409.753789,23.664496,8.615411,4.292145,260.825812,18.339401,48.086241,32.054526,...,0.000222,0.001535,0.002198,0.001243,0.001311,0.000849,0.000507,0.002656,0.000985,0.002243
1772,24.490348,25.897992,31.469344,13.553598,0.087195,-4.443822,14.428541,-0.093031,29.308845,29.475641,...,0.018833,0.009344,0.030594,0.025605,0.024317,0.038385,0.033550,0.013838,0.028716,0.022924
243,22.766074,40.849680,-94.631172,-5.157469,-8.658151,15.390614,59.812038,4.090619,21.312957,33.719862,...,0.003158,0.001996,0.002155,0.000865,0.004167,0.001985,0.002630,0.002224,0.004850,0.000384

In [18]:
inputs = tf.keras.Input(shape = (X_train.shape[1]))
expand_dims = tf.expand_dims(inputs, axis = 2)
gru = tf.keras.layers.GRU(256, return_sequences = True)(expand_dims)
flatten = tf.keras.layers.Flatten()(gru)

outputs = tf.keras.layers.Dense(3, activation = 'softmax')(flatten)

model = tf.keras.Model(inputs = inputs, outputs = outputs)

print(model.summary())

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_3 (InputLayer)         [(None, 988)]             0
_________________________________________________________________
tf.expand_dims_2 (TFOpLambda (None, 988, 1)            0
_________________________________________________________________
gru_2 (GRU)                  (None, 988, 256)          198912
_________________________________________________________________
flatten_2 (Flatten)          (None, 252928)            0
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 758787
=================================================================
Total params: 957,699
Trainable params: 957,699
Non-trainable params: 0
_________________________________________________________________
None

In [19]:
model.compile(
    optimizer = 'adam', 
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

history = model.fit(
    X_train, 
    y_train, 
    validation_split = 0.2, 
    batch_size = 32, 
    epochs = 50, 
    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor = 'val_loss',
            patience = 5, 
            restore_best_weights = True
        )
    ]
    
)

Epoch 1/50
50/50 [==============================] - 5s 62ms/step - loss: 2.9113 - accuracy: 0.7219 - val_loss: 0.6627 - val_accuracy: 0.8917
Epoch 2/50
50/50 [==============================] - 3s 61ms/step - loss: 0.5969 - accuracy: 0.8846 - val_loss: 0.5564 - val_accuracy: 0.9219
Epoch 3/50
50/50 [==============================] - 3s 59ms/step - loss: 0.2045 - accuracy: 0.9369 - val_loss: 0.4235 - val_accuracy: 0.9018
Epoch 4/50
50/50 [==============================] - 3s 60ms/step - loss: 0.1035 - accuracy: 0.9685 - val_loss: 0.5196 - val_accuracy: 0.9219
Epoch 5/50
50/50 [==============================] - 3s 59ms/step - loss: 0.0498 - accuracy: 0.9823 - val_loss: 0.5084 - val_accuracy: 0.9370
Epoch 6/50
50/50 [==============================] - 3s 61ms/step - loss: 0.0437 - accuracy: 0.9880 - val_loss: 0.5415 - val_accuracy: 0.9118
Epoch 7/50
50/50 [==============================] - 3s 60ms/step - loss: 0.0349 - accuracy: 0.9861 - val_loss: 0.3899 - val_accuracy: 0.9320
Epoch 8/50
50/50 [==============================] - 3s 59ms/step - loss: 0.0451 - accuracy: 0.9836 - val_loss: 0.4867 - val_accuracy: 0.9169
Epoch 9/50
50/50 [==============================] - 3s 61ms/step - loss: 0.0728 - accuracy: 0.9773 - val_loss: 0.5694 - val_accuracy: 0.9244
Epoch 10/50
50/50 [==============================] - 3s 60ms/step - loss: 0.0372 - accuracy: 0.9849 - val_loss: 0.6317 - val_accuracy: 0.9270
Epoch 11/50
50/50 [==============================] - 3s 61ms/step - loss: 0.0476 - accuracy: 0.9861 - val_loss: 0.5535 - val_accuracy: 0.9219
Epoch 12/50
50/50 [==============================] - 3s 60ms/step - loss: 0.0576 - accuracy: 0.9805 - val_loss: 0.6884 - val_accuracy: 0.9295

In [21]:
model_acc = model.evaluate(X_test, y_test, verbose = 0)[1]
print("Test accuracy {:.3f}  ".format(model_acc*100))

Test accuracy 96.774